import { Rsvp } from "./Rsvp.interface";

export const seedRsvps: Rsvp[] = [
  {
    guests: [{ name: "Ann Murtha" }, { name: "Victor Piotrowski" }],
    addressLabel: "Ms. Ann Murtha & Mr. Victor Piotrowski",
    streetAddress: "1004 Decesaris Dr.",
    city: "Lothian",
    state: "MD",
    zipCode: "20711",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Andres Aguilar" }, { name: "Kristin Schallhorn" }],
    addressLabel: "Mr. Andres Aguilar & Ms. Kristin Schallhorn",
    streetAddress: "603 Longfellow St. NW",
    city: "Washington",
    state: "DC",
    zipCode: "20011",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { name: "Karl Schallhorn" },
      { name: "Helen Schallhorn" },
      { name: "Nancy Schallhorn" },
      { name: "Chris Schallhorn" },
    ],
    addressLabel: "Mr. Karl, Mrs. Helen, Mrs. Nancy & Mr. Chris Schallhorn",
    streetAddress: "3330 Pfefferkorn Rd.",
    city: "West Friendship",
    state: "MD",
    zipCode: "21794",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Clare Murtha" }],
    addressLabel: "Mrs. Clare Murtha",
    streetAddress: "3144 Gracefield Rd.",
    streetAddressLineTwo: "Apt #228",
    city: "Silver Spring",
    state: "MD",
    zipCode: "20904",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { name: "Kelly Schallhorn", isAttending: false },
      { name: "Bruce Horowitz", isAttending: false },
    ],
    addressLabel: "Ms. Kelly Schallhorn & Mr. Bruce Horowitz",
    streetAddress: "5966 Westchester Park Dr.",
    streetAddressLineTwo: "Apt T1",
    city: "College Park",
    state: "MD",
    zipCode: "20722",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { name: "Courtney Schallhorn", isAttending: false },
      { name: "Darrin Wingard", isAttending: false },
    ],
    addressLabel: "Ms. Courtney Schallhorn & Mr. Darrin Wingard",
    streetAddress: "37 Norwood House Rd.",
    city: "Downingtown",
    state: "PA",
    zipCode: "19335",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { name: "Stephen Murtha", isAttending: false },
      { name: "Stephanie Murtha", isAttending: false },
    ],
    addressLabel: "Mr. Stephen & Mrs. Stephanie Murtha",
    streetAddress: "616 E Sacramento St.",
    city: "Altadena",
    state: "CA",
    zipCode: "91001",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Hunter Schallhorn", isAttending: false }],
    addressLabel: "Ms. Hunter Schallhorn",
    streetAddress: "180 High Park Ln.",
    streetAddressLineTwo: "#1210",
    city: "Silver Spring",
    state: "MD",
    zipCode: "20910",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { name: "Kara Walsh", isAttending: false },
      { name: "Mark Walsh", isAttending: false },
    ],
    addressLabel: "Mrs. Kara & Mr. Mark Walsh",
    streetAddress: "8237 S Syracuse Ct.",
    city: "Centennial",
    state: "CO",
    zipCode: "80112",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { name: "Bridget Trevillian", isAttending: false },
      { name: "Tim Trevillian", isAttending: false },
    ],
    addressLabel: "Mrs. Bridget & Mr. Tim Trevillian",
    streetAddress: "4716 NE 47th St.",
    city: "Seattle",
    state: "WA",
    zipCode: "98105-3818",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "James Murtha" }, { name: "Diane Murtha" }],
    addressLabel: "Mr. & Mrs. James Murtha",
    streetAddress: "2004 Potomac Ave.",
    city: "Alexandria",
    state: "VA",
    zipCode: "22301",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Karen Crisp", isAttending: false }],
    addressLabel: "Mrs. Karen Crisp",
    streetAddress: "436 Coho Lane",
    city: "Mansfield",
    state: "PA",
    zipCode: "16933",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Sean Murtha" }],
    addressLabel: "Mr. Sean Murtha",
    streetAddress: "529 Potomac View Parkway",
    city: "Brunswick",
    state: "MD",
    zipCode: "21726",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Maureen Dixon" }, { name: "Fred Dixon" }],
    addressLabel: "The Dixon Family",
    streetAddress: "6079 Douglas Ave.",
    city: "New Market",
    state: "MD",
    zipCode: "21774",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Brian Schallhorn", isAttending: false }],
    addressLabel: "Mr. Brian Schallhorn",
    streetAddress: "8490 Upper Sky Way",
    streetAddressLineTwo: "Apt 418",
    city: "Laurel",
    state: "MD",
    zipCode: "20723",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Taylor Schallhorn", isAttending: false }],
    addressLabel: "Mr. Taylor & Mrs. Jessica Schallhorn",
    streetAddress: "250 Dreamcatcher Trl.",
    city: "Youngsville",
    state: "NC",
    zipCode: "27596",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { name: "Megan Fitzgerald", isAttending: false },
      { name: "Timothy Fitzgerald", isAttending: false },
    ],
    addressLabel: "Mrs. Megan & Mr. Timothy Fitzgerald",
    streetAddress: "4909 Magnolia Street",
    city: "Shady Side",
    state: "MD",
    zipCode: "20764",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { name: "Christine Papanicolas", isAttending: false },
      { name: "Ron Reed", isAttending: false },
    ],
    addressLabel: "Mr. & Mrs. Christine Papanicolas",
    streetAddress: "1105 Portner Road",
    city: "Alexandria",
    state: "VA",
    zipCode: "22314",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { name: "Cristi Robinson", isAttending: false },
      { name: "Scott Robinson", isAttending: false },
    ],
    addressLabel: "Mrs. Cristi & Mr. Scott Robinson",
    streetAddress: "5421 Arnolds Court",
    city: "Columbia",
    state: "MD",
    zipCode: "21045",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Eleni Papanicolas" }],
    addressLabel: "Ms. Eleni Papanicolas",
    streetAddress: "22 M St NE",
    streetAddressLineTwo: "Apt 609",
    city: "Washington",
    state: "DC",
    zipCode: "20002",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Shane Culver" }, { name: "Elysia Culver" }],
    addressLabel: "Mr. Shane & Mrs. Elysia Culver",
    streetAddress: "16276 Connors Way",
    city: "Rockville",
    state: "MD",
    zipCode: "20855",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Andreas Papanicolas" }, { name: "Janet Papanicolas" }],
    addressLabel: "Mr. Andreas & Mrs. Janet Papanicolas",
    streetAddress: "179 R Dillenbeck Road",
    city: "Fort Plain",
    state: "NY",
    zipCode: "13339",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Jennifer Clark" }],
    addressLabel: "Ms. Jennifer Clark",
    streetAddress: "605 Dalrymple Road",
    city: "Sunderland",
    state: "MD",
    zipCode: "20689",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Ted Piotrowski" }],
    addressLabel: "Ted Piotrowski",
    streetAddress: "9615 NE 195th Cir.",
    streetAddressLineTwo: "K12",
    city: "Bothell",
    state: "WA",
    zipCode: "98011",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Ilona Piotrowski" }],
    addressLabel: "Ilona Piotrowski",
    streetAddress: "1037 Hyperion Ave.",
    streetAddressLineTwo: "#108",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90029",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Monika Piotrowska" }, { name: "Matt Mosdell" }],
    addressLabel: "Monika Piotrowska & Matt Mosdell",
    streetAddress: "117 Vaughn Drive",
    city: "Albany",
    state: "NY",
    zipCode: "12203",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { name: "Robert Jonsson" },
      { name: "Maria Jonsson" },
      { name: "Roderic Jonsson" },
      { name: "Jennifer Jonsson" },
    ],
    addressLabel: "Mr. & Mrs. Robert Jonsson and family",
    streetAddress: "Chamstrasse 62 Ch-8934",
    city: "Knonau",
    state: "Switzerland",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Matt Ellisor" }, { name: "Ana Carolina Ellisor" }],
    addressLabel: "Mr. & Mrs. Matt Ellisor",
    streetAddress: "13711 Eldon Park Ct.",
    city: "Cypress",
    state: "TX",
    zipCode: "77429",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Carlos Emilo Aguilar" }, { name: "Daniela Aguilar" }],
    addressLabel: "Dr. & Mrs. Carlos Emilio Aguilar",
    streetAddress: "2293 Devon Circle.",
    city: "Ann Arbor",
    state: "MI",
    zipCode: "48105",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Carlos Pimentel" }, { name: "Maya Pimentel" }],
    addressLabel: "Dr. & Mrs. Carlos Pimentel",
    streetAddress: "113 Bell Meadow Place",
    city: "Charlotte",
    state: "NC",
    zipCode: "28211",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Javier Pere" }, { name: "Ana Pere" }],
    addressLabel: "Drs. Javier & Ana Pere",
    streetAddress: "3020 Lakeshore Dr.",
    city: "Lima",
    state: "OH",
    zipCode: "45806",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Jorge Camacho" }, { name: "Glenda Camacho" }],
    addressLabel: "Dr. & Mrs. Jorge Camacho",
    streetAddress: "8204 SW 16th Place.",
    city: "Gainsville",
    state: "FL",
    zipCode: "32607",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Edwin Schenmankewitz" }, { name: "Gigi Shemankewitz" }],
    addressLabel: "Drs. Edwin & Gigi Schemankewitz",
    streetAddress: "5380 Redfield Dr.",
    city: "Dunwoody",
    state: "GA",
    zipCode: "30338",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Luis Eduardo Fayad" }, { name: "Maria Delia Fayad" }],
    addressLabel: "Dr. & Mrs. Luis Eduardo Fayad",
    streetAddress: "3614 Bellefontaine St.",
    city: "Houston",
    state: "TX",
    zipCode: "77025",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Danny Delgado" }],
    addressLabel: "Dr. Danny Delgado",
    streetAddress: "6383 Golden Eye Glen.",
    city: "Lakewood Ranch",
    state: "FL",
    zipCode: "34202",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Fabian Ramos" }, { name: "" }],
    addressLabel: "Dr. & Mrs. Fabian Ramos",
    streetAddress: "66907 Westchester Circle.",
    city: "Braidington",
    state: "FL",
    zipCode: "34202",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Jorge Gilbert" }, { name: "Fabyola Gilbert" }],
    addressLabel: "Dr. & Mrs. Jorge Gilbert",
    streetAddress: "2905 W.Latigo Trail.",
    city: "Sioux Falls",
    state: "SD",
    zipCode: "57108",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Mark Provenza" }, { name: "Rhonda Provenza" }],
    addressLabel: "Dr. & Mrs. Mark Provenza",
    streetAddress: "1932 Shaded Willow Lane",
    city: "Shreveport",
    state: "LA",
    zipCode: "71106",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Fernando Quevedo" }, { name: "Lisa Quevedo" }],
    addressLabel: "Dr. & Mrs. Fernando Quevedo",
    streetAddress: "2106 Abigail Lane SW.",
    city: "Rochester",
    state: "MN",
    zipCode: "55902",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Jorge Pietri" }, { name: "Jenny Pietri" }],
    addressLabel: "Mr. & Mrs. Jorge Pietri",
    streetAddress: "7559 Caprio Dr.",
    city: "Boynton Beach",
    state: "FL",
    zipCode: "33472",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Jim McGee" }, { name: "Renee McGee" }],
    addressLabel: "Mr. & Mrs. Jim McGee",
    streetAddress: "4540 Cambridge Circle",
    city: "Shreveport",
    state: "LA",
    zipCode: "71107",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "William Dorroh" }, { name: "Katherine Dorroh" }],
    addressLabel: "Mr. & Mrs. William Dorroh",
    streetAddress: "11260 Heritage Oaks",
    city: "Shreveport",
    state: "LA",
    zipCode: "71106",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Javier Pere" }, { name: "Megan Pere" }],
    addressLabel: "Mr. & Mrs. Javier A. Pere",
    streetAddress: "2195 Loudenslager Dr.",
    city: "Thompsons Station",
    state: "TN",
    zipCode: "37179",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Christ Balich" }, { name: "Ana Balich" }],
    addressLabel: "Mr. & Mrs. Christ Balich",
    streetAddress: "3851 S Lowe Ave.",
    city: "Chicago",
    state: "IL",
    zipCode: "60609",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Maria Pere" }],
    addressLabel: "Dr. Maria Pere",
    streetAddress: "122 Reizenstein Way.",
    city: "Pittsburgh",
    state: "PA",
    zipCode: "15206",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Ben Yeoman" }, { name: "Nathalie Yeoman" }],
    addressLabel: "Mr. & Mrs. Ben Yeoman",
    streetAddress: "906 Richland Drive",
    city: "Charlotte",
    state: "NC",
    zipCode: "28211",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Jeffrey Cargill" }, { name: "Crystal Cargill" }],
    addressLabel: "Mr. Jeffrey & Mrs. Crystal Cargill",
    streetAddress: "316 2nd St. SE",
    city: "Washington",
    state: "DC",
    zipCode: "20003",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Justin Brandt" }],
    addressLabel: "Mr. Justin Brandt",
    streetAddress: "101 N Croft Ave.",
    streetAddressLineTwo: "Apartment 206",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90048",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Chance Lee" }, { name: "Lily Castro" }],
    addressLabel: "Mr. Chance Lee & Mrs. Lily Castro",
    streetAddress: "320 N 18th St.",
    city: "Philadelphia",
    state: "PA",
    zipCode: "19103",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Valerie Aguilar" }],
    addressLabel: "Ms. Valerie Aguilar",
    streetAddress: "3 Hanover Square",
    streetAddressLineTwo: "Apartment 4C",
    city: "New York",
    state: "NY",
    zipCode: "10004",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Stephen Chandler" }, { name: "Hannah Chandler" }],
    addressLabel: "Mr. Stephen & Mrs. Hannah Chandler",
    streetAddress: "16407 Shefford Dr.",
    city: "Midlothian",
    state: "VA",
    zipCode: "23112",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Jordan Stone" }, { name: "Jordan Yates" }],
    addressLabel: "Mr. Jordan Stone & Mrs. Jordan Yates",
    streetAddress: "5607B Louisiana Ave.",
    city: "Nashville",
    state: "TN",
    zipCode: "37209",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Alexia Aguilar" }, { name: "Priscilla Canals" }],
    addressLabel: "Ms. Alexia Aguilar & Ms. Priscilla Canals",
    streetAddress: "610 N Elmer Ave.",
    streetAddressLineTwo: "2nd Floor",
    city: "Sayre",
    state: "PA",
    zipCode: "18840",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Kamal Fulani" }, { name: "Bina Fulani" }],
    addressLabel: "Mr. Kamal & Mrs. Bina Fulani",
    streetAddress: "9783 Lanward Dr.",
    city: "Dallas",
    state: "TX",
    zipCode: "75238",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Gregory Hill" }, { name: "Sicong Liang" }],
    addressLabel: "Mr. Gregory Hill & Ms. Sicong Liang",
    streetAddress: "1810 Cahill Ave.",
    city: "Nashville",
    state: "TN",
    zipCode: "37206",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Evan Jacobs" }, { name: "Jessica Jacobs" }],
    addressLabel: "Mr. Evan & Mrs. Jessica Jacobs",
    streetAddress: "745 South 7th St.",
    city: "Philadelphia",
    state: "PA",
    zipCode: "19147",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Laurel Fedder" }],
    addressLabel: "Ms. Laurel Fedder",
    streetAddress: "154 Beaver St.",
    city: "San Francisco",
    state: "CA",
    zipCode: "94114",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Jonathan Fredi" }, { name: "Erin Fredi" }],
    addressLabel: "Mr. Jonathan & Mrs. Erin Fredi",
    streetAddress: "9015 Fringewood Dr.",
    city: "Dallas",
    state: "TX",
    zipCode: "75228",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Ramon Bertucci" }, { name: "Stacie Bertucci" }],
    addressLabel: "Mr. Ramon & Mrs. Stacie Bertucci",
    streetAddress: "1006 Vista Bell Dr.",
    city: "Cave Springs",
    state: "AR",
    zipCode: "72718",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Connor Mackenzie" }, { name: "Meaghan Conner" }],
    addressLabel: "Mr. Connor Mackenzie & Ms. Meaghan Conner",
    streetAddress: "732 Lamont St. NW",
    streetAddressLineTwo: "Apartment 301",
    city: "Washington",
    state: "DC",
    zipCode: "20010",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Kyle Eason" }],
    addressLabel: "Mr. Kyle Eason",
    streetAddress: "5512 Oakmont Circle",
    city: "Nashville",
    state: "TN",
    zipCode: "37209",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Andrew Patton" }, { name: "Suzanne Patton" }],
    addressLabel: "Mr. Andrew & Mrs. Suzanne Patton",
    streetAddress: "1044 Saint Francis Way",
    city: "Shreveport",
    state: "LA",
    zipCode: "71106",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Henry Hilario" }, { name: "Danielle Hilario" }],
    addressLabel: "Mr. Henry & Mrs. Danielle Hilario",
    streetAddress: "2860 Covington Circle",
    city: "Shreveport",
    state: "LA",
    zipCode: "71106",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Magali Cabezas" }],
    addressLabel: "Srta. Magali Cabezas",
    streetAddress: "",
    city: "Guayaquil",
    state: "Ecuador",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Raul Doria" }, { name: "Katy Doria" }],
    addressLabel: "Dr. & Mrs. Raul Doria",
    streetAddress: "2816 General Pershing Street",
    city: "New Orleans",
    state: "LA",
    zipCode: "70115",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Maria Aguilar" }],
    addressLabel: "Mrs. Maria Aguilar",
    streetAddress: "",
    city: "Guayaquil",
    state: "Ecuador",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Carlos Aguilar" }, { name: "Gladys Maria Aguilar" }],
    addressLabel: "Mr. & Mrs. Carlos Aguilar",
    streetAddress: "",
    city: "Guayaquil",
    state: "Ecuador",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Agusto Aguirre" }, { name: "Graciella Aguirre" }],
    addressLabel: "Mr. & Mrs. Augusto Aguirre",
    streetAddress: "",
    city: "Guayaquil",
    state: "Ecuador",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Monica Aguirre" }],
    addressLabel: "Ms. Monica Aguirre",
    streetAddress: "",
    city: "Guayaquil",
    state: "Ecuador",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { name: "Lorena Aguirre" },
      { name: "Guillermo Aguirre" },
      { name: "Domenica Aguirre" },
      { name: "" },
    ],
    addressLabel: "Ms. Lorena Aguirre and family",
    streetAddress: "",
    city: "Guayaquil",
    state: "Ecuador",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Grace Aguirre" }],
    addressLabel: "Ms. Grace Aguirre",
    streetAddress: "",
    city: "Guayaquil",
    state: "Ecuador",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Eduardo Peña" }, { name: "Soledad Peña" }],
    addressLabel: "Drs. Eduardo & Soledad Peña",
    streetAddress: "",
    city: "Guayaquil",
    state: "Ecuador",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Alvaro Noboa" }, { name: "Annabella Noboa" }],
    addressLabel: "Mr. & Dr. Alvaro Noboa",
    streetAddress: "",
    city: "Guayaquil",
    state: "Ecuador",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Humberto Aguilar" }, { name: "Kattya Aguilar" }],
    addressLabel: "Dr. Humberto & Mrs. Kattya Aguilar",
    streetAddress: "1012 Bayberry Circle",
    city: "Shreveport",
    state: "LA",
    zipCode: "71106",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  //   { guests: [{ name: "Ally" }] } as Rsvp,
  //   { guests: [{ name: "Kait" }] } as Rsvp,
  //   { guests: [{ name: "Sean" }] } as Rsvp,
  {
    guests: [{ name: "Christopher Ingram" }, { name: "Cathy Ingram" }],
    addressLabel: "Dr. and Mrs. Christopher Ingram",
    streetAddress: "1122 E. 5th Street",
    city: "Natchitoches",
    state: "LA",
    zipCode: "71457",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ name: "Martin Aviles" }, { name: "Carmen Aviles" }],
    addressLabel: "Dr. and Mrs. Martin Aviles",
    streetAddress: "412 Williams Avenue",
    city: "Natchitoches",
    state: "LA",
    zipCode: "71457",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
];

/* TODO: 
- Update entries for Ally, Kait, and Sean
*/
