import { Rsvp } from "./Rsvp.interface";

export const seedRsvps: Rsvp[] = [
  {
    guests: [
      { firstName: "Ann", lastName: "Murtha" },
      { firstName: "Victor", lastName: "Piotrowski" },
    ],
    addressLabel: "Ms. Ann Murtha & Mr. Victor Piotrowski",
    streetAddress: "1004 Decesaris Dr.",
    city: "Lothian",
    state: "MD",
    zipCode: "20711",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Andres", lastName: "Aguilar" },
      { firstName: "Kristin", lastName: "Schallhorn" },
    ],
    addressLabel: "Mr. Andres Aguilar & Ms. Kristin Schallhorn",
    streetAddress: "603 Longfellow St. NW",
    city: "Washington",
    state: "DC",
    zipCode: "20011",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Karl", lastName: "Schallhorn" },
      { firstName: "Helen", lastName: "Schallhorn" },
      { firstName: "Nancy", lastName: "Schallhorn" },
      { firstName: "Chris", lastName: "Schallhorn" },
    ],
    addressLabel: "Mr. Karl, Mrs. Helen, Mrs. Nancy & Mr. Chris Schallhorn",
    streetAddress: "3330 Pfefferkorn Rd.",
    city: "West Friendship",
    state: "MD",
    zipCode: "21794",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ firstName: "Clare", lastName: "Murtha" }],
    addressLabel: "Mrs. Clare Murtha",
    streetAddress: "3144 Gracefield Rd.",
    streetAddressLineTwo: "Apt #228",
    city: "Silver Spring",
    state: "MD",
    zipCode: "20904",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Kelly", lastName: "Schallhorn" },
      { firstName: "Bruce", lastName: "Horowitz" },
    ],
    addressLabel: "Ms. Kelly Schallhorn & Mr. Bruce Horowitz",
    streetAddress: "5966 Westchester Park Dr.",
    streetAddressLineTwo: "Apt T1",
    city: "College Park",
    state: "MD",
    zipCode: "20722",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Courtney", lastName: "Schallhorn" },
      { firstName: "Darrin", lastName: "Wingard" },
    ],
    addressLabel: "Ms. Courtney Schallhorn & Mr. Darrin Wingard",
    streetAddress: "37 Norwood House Rd.",
    city: "Downingtown",
    state: "PA",
    zipCode: "19335",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Stephen", lastName: "Murtha" },
      { firstName: "Stephanie", lastName: "Murtha" },
    ],
    addressLabel: "Mr. Stephen & Mrs. Stephanie Murtha",
    streetAddress: "616 E Sacramento St.",
    city: "Altadena",
    state: "CA",
    zipCode: "91001",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ firstName: "Hunter Schallhorn", lastName: "Schallhorn" }],
    addressLabel: "Ms. Hunter Schallhorn",
    streetAddress: "180 High Park Ln.",
    streetAddressLineTwo: "#1210",
    city: "Silver Spring",
    state: "MD",
    zipCode: "20910",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Kara", lastName: "Walsh" },
      { firstName: "Mark", lastName: "Walsh" },
    ],
    addressLabel: "Mrs. Kara & Mr. Mark Walsh",
    streetAddress: "8237 S Syracuse Ct.",
    city: "Centennial",
    state: "CO",
    zipCode: "80112",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Bridget", lastName: "Trevillian" },
      { firstName: "Tim", lastName: "Trevillian" },
    ],
    addressLabel: "Mrs. Bridget & Mr. Tim Trevillian",
    streetAddress: "4716 NE 47th St.",
    city: "Seattle",
    state: "WA",
    zipCode: "98105-3818",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "James", lastName: "Murtha" },
      { firstName: "Diane", lastName: "Murtha" },
    ],
    addressLabel: "Mr. & Mrs. James Murtha",
    streetAddress: "2004 Potomac Ave.",
    city: "Alexandria",
    state: "VA",
    zipCode: "22301",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ firstName: "Karen", lastName: "Crisp" }],
    addressLabel: "Mrs. Karen Crisp",
    streetAddress: "436 Coho Lane",
    city: "Mansfield",
    state: "PA",
    zipCode: "16933",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ firstName: "Sean", lastName: "Murtha" }],
    addressLabel: "Mr. Sean Murtha",
    streetAddress: "529 Potomac View Parkway",
    city: "Brunswick",
    state: "MD",
    zipCode: "21726",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Maureen", lastName: "Dixon" },
      { firstName: "Fred", lastName: "Dixon" },
      { firstName: "Ally", lastName: "Dixon" },
    ],
    addressLabel: "Mr. Fred, Mrs. Maureen & Ms. Ally Dixon",
    streetAddress: "6079 Douglas Ave.",
    city: "New Market",
    state: "MD",
    zipCode: "21774",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ firstName: "Brian", lastName: "Schallhorn" }],
    addressLabel: "Mr. Brian Schallhorn",
    streetAddress: "8490 Upper Sky Way",
    streetAddressLineTwo: "Apt 418",
    city: "Laurel",
    state: "MD",
    zipCode: "20723",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ firstName: "Taylor", lastName: "Schallhorn" }],
    addressLabel: "Mr. Taylor & Mrs. Jessica Schallhorn",
    streetAddress: "250 Dreamcatcher Trl.",
    city: "Youngsville",
    state: "NC",
    zipCode: "27596",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Megan", lastName: "Fitzgerald" },
      { firstName: "Timothy", lastName: "Fitzgerald" },
    ],
    addressLabel: "Mrs. Megan & Mr. Timothy Fitzgerald",
    streetAddress: "4909 Magnolia Street",
    city: "Shady Side",
    state: "MD",
    zipCode: "20764",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Christine", lastName: "Papanicolas" },
      { firstName: "Ron", lastName: "Reed" },
    ],
    addressLabel: "Mr. & Mrs. Christine Papanicolas",
    streetAddress: "1105 Portner Road",
    city: "Alexandria",
    state: "VA",
    zipCode: "22314",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Cristi", lastName: "Robinson" },
      { firstName: "Scott", lastName: "Robinson" },
    ],
    addressLabel: "Mrs. Cristi & Mr. Scott Robinson",
    streetAddress: "5421 Arnolds Court",
    city: "Columbia",
    state: "MD",
    zipCode: "21045",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ firstName: "Eleni", lastName: "Papanicolas" }],
    addressLabel: "Ms. Eleni Papanicolas",
    streetAddress: "22 M St NE",
    streetAddressLineTwo: "Apt 609",
    city: "Washington",
    state: "DC",
    zipCode: "20002",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Shane", lastName: "Culver" },
      { firstName: "Elysia", lastName: "Culver" },
    ],
    addressLabel: "Mr. Shane & Mrs. Elysia Culver",
    streetAddress: "16276 Connors Way",
    city: "Rockville",
    state: "MD",
    zipCode: "20855",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Andreas", lastName: "Papanicolas" },
      { firstName: "Janet", lastName: "Papanicolas" },
    ],
    addressLabel: "Mr. Andreas & Mrs. Janet Papanicolas",
    streetAddress: "179 R Dillenbeck Road",
    city: "Fort Plain",
    state: "NY",
    zipCode: "13339",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ firstName: "Jennifer", lastName: "Clark" }],
    addressLabel: "Ms. Jennifer Clark",
    streetAddress: "605 Dalrymple Road",
    city: "Sunderland",
    state: "MD",
    zipCode: "20689",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Ted", lastName: "Piotrowski" },
      { firstName: "Cassondra", lastName: "Warme Prutsman" },
    ],
    addressLabel: "Mr. Ted Piotrowski & Ms. Cassondra Warme Prutsman",
    streetAddress: "9615 NE 195th Cir.",
    streetAddressLineTwo: "K12",
    city: "Bothell",
    state: "WA",
    zipCode: "98011",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ firstName: "Ilona", lastName: "Piotrowski" }],
    addressLabel: "Ilona Piotrowski",
    streetAddress: "1037 Hyperion Ave.",
    streetAddressLineTwo: "#108",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90029",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Monika", lastName: "Piotrowski" },
      { firstName: "Matt", lastName: "Mosdell" },
    ],
    addressLabel: "Monika Piotrowska & Matt Mosdell",
    streetAddress: "117 Vaughn Drive",
    city: "Albany",
    state: "NY",
    zipCode: "12203",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Robert", lastName: "Jonsson" },
      { firstName: "Maria", lastName: "Jonsson" },
      { firstName: "Roderic", lastName: "Jonsson" },
      { firstName: "Jennifer", lastName: "Jonsson" },
    ],
    addressLabel: "Mr. & Mrs. Robert Jonsson and family",
    streetAddress: "Chamstrasse 62 Ch-8934",
    city: "Knonau",
    state: "Switzerland",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Matt", lastName: "Ellisor" },
      { firstName: "Ana", middleName: "Carolina", lastName: "Ellisor" },
    ],
    addressLabel: "Mr. & Mrs. Matt Ellisor",
    streetAddress: "13711 Eldon Park Ct.",
    city: "Cypress",
    state: "TX",
    zipCode: "77429",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Carlos", lastName: "Aguilar", middleName: "Emilio" },
      { firstName: "Daniela", lastName: "Aguilar" },
    ],
    addressLabel: "Dr. & Mrs. Carlos Emilio Aguilar",
    streetAddress: "2293 Devon Circle.",
    city: "Ann Arbor",
    state: "MI",
    zipCode: "48105",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Carlos", lastName: "Pimentel" },
      { firstName: "Maya", lastName: "Pimentel" },
    ],
    addressLabel: "Dr. & Mrs. Carlos Pimentel",
    streetAddress: "113 Bell Meadow Place",
    city: "Charlotte",
    state: "NC",
    zipCode: "28211",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Javier", lastName: "Pere" },
      { firstName: "Ana", lastName: "Pere" },
    ],
    addressLabel: "Drs. Javier & Ana Pere",
    streetAddress: "3020 Lakeshore Dr.",
    city: "Lima",
    state: "OH",
    zipCode: "45806",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Jorge", lastName: "Camacho" },
      { firstName: "Glenda", lastName: "Camacho" },
    ],
    addressLabel: "Dr. & Mrs. Jorge Camacho",
    streetAddress: "8204 SW 16th Place.",
    city: "Gainsville",
    state: "FL",
    zipCode: "32607",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Edwin", lastName: "Schenmankewitz" },
      { firstName: "Gigi", lastName: "Shemankewitz" },
    ],
    addressLabel: "Drs. Edwin & Gigi Schemankewitz",
    streetAddress: "5380 Redfield Dr.",
    city: "Dunwoody",
    state: "GA",
    zipCode: "30338",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Luis", middleName: "Eduardo", lastName: "Fayad" },
      { firstName: "Maria", middleName: "Delia", lastName: "Fayad" },
    ],
    addressLabel: "Dr. & Mrs. Luis Eduardo Fayad",
    streetAddress: "3614 Bellefontaine St.",
    city: "Houston",
    state: "TX",
    zipCode: "77025",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ firstName: "Danny", lastName: "Delgado" }],
    addressLabel: "Dr. Danny Delgado",
    streetAddress: "6383 Golden Eye Glen.",
    city: "Lakewood Ranch",
    state: "FL",
    zipCode: "34202",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Fabian", lastName: "Ramos" },
      { firstName: "Kathy", lastName: "Ramos" },
    ],
    addressLabel: "Dr. & Mrs. Fabian Ramos",
    streetAddress: "66907 Westchester Circle.",
    city: "Braidington",
    state: "FL",
    zipCode: "34202",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Jorge", lastName: "Gilbert" },
      { firstName: "Fabyola", lastName: "Gilbert" },
    ],
    addressLabel: "Dr. & Mrs. Jorge Gilbert",
    streetAddress: "2905 W.Latigo Trail.",
    city: "Sioux Falls",
    state: "SD",
    zipCode: "57108",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Mark", lastName: "Provenza" },
      { firstName: "Rhonda", lastName: "Provenza" },
    ],
    addressLabel: "Dr. & Mrs. Mark Provenza",
    streetAddress: "1932 Shaded Willow Lane",
    city: "Shreveport",
    state: "LA",
    zipCode: "71106",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Fernando", lastName: "Quevedo" },
      { firstName: "Lisa", lastName: "Quevedo" },
    ],
    addressLabel: "Dr. & Mrs. Fernando Quevedo",
    streetAddress: "2106 Abigail Lane SW.",
    city: "Rochester",
    state: "MN",
    zipCode: "55902",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Jorge", lastName: "Pietri" },
      { firstName: "Jenny", lastName: "Pietri" },
    ],
    addressLabel: "Mr. & Mrs. Jorge Pietri",
    streetAddress: "7559 Caprio Dr.",
    city: "Boynton Beach",
    state: "FL",
    zipCode: "33472",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Jim", lastName: "McGee" },
      { firstName: "Renee", lastName: "McGee" },
    ],
    addressLabel: "Mr. & Mrs. Jim McGee",
    streetAddress: "4540 Cambridge Circle",
    city: "Shreveport",
    state: "LA",
    zipCode: "71107",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "William", lastName: "Dorroh" },
      { firstName: "Katherine", lastName: "Dorroh" },
    ],
    addressLabel: "Mr. & Mrs. William Dorroh",
    streetAddress: "11260 Heritage Oaks",
    city: "Shreveport",
    state: "LA",
    zipCode: "71106",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Javier", lastName: "Pere" },
      { firstName: "Megan", lastName: "Pere" },
    ],
    addressLabel: "Mr. & Mrs. Javier A. Pere",
    streetAddress: "2195 Loudenslager Dr.",
    city: "Thompsons Station",
    state: "TN",
    zipCode: "37179",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Christ", lastName: "Balich" },
      { firstName: "Ana", lastName: "Balich" },
    ],
    addressLabel: "Mr. & Mrs. Christ Balich",
    streetAddress: "3851 S Lowe Ave.",
    city: "Chicago",
    state: "IL",
    zipCode: "60609",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ firstName: "Maria", lastName: "Pere" }],
    addressLabel: "Dr. Maria Pere",
    streetAddress: "122 Reizenstein Way.",
    city: "Pittsburgh",
    state: "PA",
    zipCode: "15206",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Ben", lastName: "Yeoman" },
      { firstName: "Nathalie", lastName: "Yeoman" },
    ],
    addressLabel: "Mr. & Mrs. Ben Yeoman",
    streetAddress: "906 Richland Drive",
    city: "Charlotte",
    state: "NC",
    zipCode: "28211",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Jeffrey", lastName: "Cargill" },
      { firstName: "Crystal", lastName: "Cargill" },
    ],
    addressLabel: "Mr. Jeffrey & Mrs. Crystal Cargill",
    streetAddress: "316 2nd St. SE",
    city: "Washington",
    state: "DC",
    zipCode: "20003",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ firstName: "Justin", lastName: "Brandt" }],
    addressLabel: "Mr. Justin Brandt",
    streetAddress: "101 N Croft Ave.",
    streetAddressLineTwo: "Apartment 206",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90048",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Chance", lastName: "Lee" },
      { firstName: "Lily", lastName: "Castro" },
    ],
    addressLabel: "Mr. Chance Lee & Mrs. Lily Castro",
    streetAddress: "320 N 18th St.",
    city: "Philadelphia",
    state: "PA",
    zipCode: "19103",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ firstName: "Valerie", lastName: "Aguilar" }],
    addressLabel: "Ms. Valerie Aguilar",
    streetAddress: "3 Hanover Square",
    streetAddressLineTwo: "Apartment 4C",
    city: "New York",
    state: "NY",
    zipCode: "10004",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Stephen", lastName: "Chandler" },
      { firstName: "Hannah", lastName: "Chandler" },
    ],
    addressLabel: "Mr. Stephen & Mrs. Hannah Chandler",
    streetAddress: "16407 Shefford Dr.",
    city: "Midlothian",
    state: "VA",
    zipCode: "23112",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Jordan", lastName: "Stone" },
      { firstName: "Jordan", lastName: "Yates" },
    ],
    addressLabel: "Mr. Jordan Stone & Mrs. Jordan Yates",
    streetAddress: "5607B Louisiana Ave.",
    city: "Nashville",
    state: "TN",
    zipCode: "37209",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Alexia", lastName: "Aguilar" },
      { firstName: "Priscilla", lastName: "Canals" },
    ],
    addressLabel: "Ms. Alexia Aguilar & Ms. Priscilla Canals",
    streetAddress: "610 N Elmer Ave.",
    streetAddressLineTwo: "2nd Floor",
    city: "Sayre",
    state: "PA",
    zipCode: "18840",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Kamal", lastName: "Fulani" },
      { firstName: "Bina", lastName: "Fulani" },
    ],
    addressLabel: "Mr. Kamal & Mrs. Bina Fulani",
    streetAddress: "9783 Lanward Dr.",
    city: "Dallas",
    state: "TX",
    zipCode: "75238",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Gregory", lastName: "Hill" },
      { firstName: "Sicong", lastName: "Liang" },
    ],
    addressLabel: "Mr. Gregory Hill & Ms. Sicong Liang",
    streetAddress: "1810 Cahill Ave.",
    city: "Nashville",
    state: "TN",
    zipCode: "37206",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Evan", lastName: "Jacobs" },
      { firstName: "Jessica", lastName: "Jacobs" },
    ],
    addressLabel: "Mr. Evan & Mrs. Jessica Jacobs",
    streetAddress: "745 South 7th St.",
    city: "Philadelphia",
    state: "PA",
    zipCode: "19147",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ firstName: "Laurel", lastName: "Fedder" }],
    addressLabel: "Ms. Laurel Fedder",
    streetAddress: "154 Beaver St.",
    city: "San Francisco",
    state: "CA",
    zipCode: "94114",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Jonathan", lastName: "Fredi" },
      { firstName: "Erin", lastName: "Fredi" },
    ],
    addressLabel: "Mr. Jonathan & Mrs. Erin Fredi",
    streetAddress: "9015 Fringewood Dr.",
    city: "Dallas",
    state: "TX",
    zipCode: "75228",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Ramon", lastName: "Bertucci" },
      { firstName: "Stacie", lastName: "Bertucci" },
    ],
    addressLabel: "Mr. Ramon & Mrs. Stacie Bertucci",
    streetAddress: "1006 Vista Bell Dr.",
    city: "Cave Springs",
    state: "AR",
    zipCode: "72718",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Connor", lastName: "Mackenzie" },
      { firstName: "Meaghan", lastName: "Conner" },
    ],
    addressLabel: "Mr. Connor Mackenzie & Ms. Meaghan Conner",
    streetAddress: "732 Lamont St. NW",
    streetAddressLineTwo: "Apartment 301",
    city: "Washington",
    state: "DC",
    zipCode: "20010",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ firstName: "Kyle", lastName: "Eason" }],
    addressLabel: "Mr. Kyle Eason",
    streetAddress: "5512 Oakmont Circle",
    city: "Nashville",
    state: "TN",
    zipCode: "37209",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Andrew", lastName: "Patton" },
      { firstName: "Suzanne", lastName: "Patton" },
    ],
    addressLabel: "Mr. Andrew & Mrs. Suzanne Patton",
    streetAddress: "1044 Saint Francis Way",
    city: "Shreveport",
    state: "LA",
    zipCode: "71106",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Henry", lastName: "Hilario" },
      { firstName: "Danielle", lastName: "Hilario" },
    ],
    addressLabel: "Mr. Henry & Mrs. Danielle Hilario",
    streetAddress: "2860 Covington Circle",
    city: "Shreveport",
    state: "LA",
    zipCode: "71106",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ firstName: "Magali", lastName: "Cabezas" }],
    addressLabel: "Srta. Magali Cabezas",
    streetAddress: "",
    city: "Guayaquil",
    state: "Ecuador",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Raul", lastName: "Doria" },
      { firstName: "Katy", lastName: "Doria" },
    ],
    addressLabel: "Dr. & Mrs. Raul Doria",
    streetAddress: "2816 General Pershing Street",
    city: "New Orleans",
    state: "LA",
    zipCode: "70115",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ firstName: "Maria", lastName: "Aguilar" }],
    addressLabel: "Mrs. Maria Aguilar",
    streetAddress: "",
    city: "Guayaquil",
    state: "Ecuador",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Carlos", lastName: "Aguilar" },
      { firstName: "Gladys", middleName: "Maria", lastName: "Aguilar" },
    ],
    addressLabel: "Mr. & Mrs. Carlos Aguilar",
    streetAddress: "",
    city: "Guayaquil",
    state: "Ecuador",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Agusto", lastName: "Aguirre" },
      { firstName: "Graciella", lastName: "Aguirre" },
    ],
    addressLabel: "Mr. & Mrs. Augusto Aguirre",
    streetAddress: "",
    city: "Guayaquil",
    state: "Ecuador",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ firstName: "Monica", lastName: "Aguirre" }],
    addressLabel: "Ms. Monica Aguirre",
    streetAddress: "",
    city: "Guayaquil",
    state: "Ecuador",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Lorena", lastName: "Aguirre" },
      { firstName: "Guillermo", lastName: "Aguirre" },
      { firstName: "Domenica", lastName: "Aguirre" },
      { firstName: "Ricardo", lastName: "Aguilar" },
    ],
    addressLabel: "Ms. Lorena Aguirre and family",
    streetAddress: "",
    city: "Guayaquil",
    state: "Ecuador",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [{ firstName: "Grace", lastName: "Aguirre" }],
    addressLabel: "Ms. Grace Aguirre",
    streetAddress: "",
    city: "Guayaquil",
    state: "Ecuador",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Eduardo", lastName: "Peña" },
      { firstName: "Soledad", lastName: "Peña" },
    ],
    addressLabel: "Drs. Eduardo & Soledad Peña",
    streetAddress: "",
    city: "Guayaquil",
    state: "Ecuador",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Alvaro", lastName: "Noboa" },
      { firstName: "Annabella", lastName: "Noboa" },
    ],
    addressLabel: "Mr. & Dr. Alvaro Noboa",
    streetAddress: "",
    city: "Guayaquil",
    state: "Ecuador",
    zipCode: "",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Humberto", lastName: "Aguilar" },
      { firstName: "Kattya", lastName: "Aguilar" },
    ],
    addressLabel: "Dr. Humberto & Mrs. Kattya Aguilar",
    streetAddress: "1012 Bayberry Circle",
    city: "Shreveport",
    state: "LA",
    zipCode: "71106",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Christopher", lastName: "Ingram" },
      { firstName: "Cathy", lastName: "Ingram" },
    ],
    addressLabel: "Dr. and Mrs. Christopher Ingram",
    streetAddress: "1122 E. 5th Street",
    city: "Natchitoches",
    state: "LA",
    zipCode: "71457",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
  {
    guests: [
      { firstName: "Martin", lastName: "Aviles" },
      { firstName: "Carmen", lastName: "Aviles" },
    ],
    addressLabel: "Dr. and Mrs. Martin Aviles",
    streetAddress: "412 Williams Avenue",
    city: "Natchitoches",
    state: "LA",
    zipCode: "71457",
    emailAddress: "",
    hasRsvped: false,
    dietaryRestrictions: "",
  },
];

/* TODO: 
- Update entries for Kait, and Sean
*/
